package cloudonboarding

import (
	"context"

	"github.com/PaloAltoNetworks/cortex-cloud-go/cloudonboarding"
	models "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/cloud_onboarding"
	providerModels "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/provider"
	"github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/util"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	//"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource = &OutpostTemplateDataSource{}
)

// NewOutpostTemplateDataSource is a helper function to simplify the provider implementation.
func NewOutpostTemplateDataSource() datasource.DataSource {
	return &OutpostTemplateDataSource{}
}

// OutpostTemplateDataSource is the data source implementation.
type OutpostTemplateDataSource struct {
	client *cloudonboarding.Client
}

// Metadata returns the data source type name.
func (r *OutpostTemplateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_outpost_template"
}

// Schema defines the schema for the data source.
func (r *OutpostTemplateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Provides a download link for a CSP outpost template.",
		Attributes: map[string]schema.Attribute{
			"cloud_provider": schema.StringAttribute{
				Description: "The cloud service provider. Possible values are: \"AWS\", \"AZURE\", \"GCP\"",
				Required:    true,
			},
			"custom_resources_tags": schema.SetNestedAttribute{
				Description: "Tags applied to any new resource created by Cortex Cloud in the cloud environment.",
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Description: "The tag key.",
							Required:    true,
						},
						"value": schema.StringAttribute{
							Description: "The tag value.",
							Required:    true,
						},
					},
				},
			},
			"terraform_module_url": schema.StringAttribute{
				Description: "The download link for the Terraform module that is generated by Cortex Cloud upon successful creation of the outpost template resource. You may download and deploy this module to create the required infrastructure to conduct cloud workload scans in the configured cloud account.",
				Computed:    true,
			},
		},
	}
}

// Configure adds the provider-configured client to the data source.
func (r *OutpostTemplateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*providerModels.CortexCloudSDKClients)

	if !ok {
		util.AddUnexpectedDataSourceConfigurationTypeError(&resp.Diagnostics, "*cloudonboarding.Client", req.ProviderData)
		return
	}

	r.client = client.CloudOnboarding
}

// Read refreshes the Terraform state with the latest data.
func (r *OutpostTemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	defer util.PanicHandler(&resp.Diagnostics)

	var data models.OutpostTemplateModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// If terraform_module_url is already known, do not re-create
	if !data.TerraformModuleURL.IsNull() {
		return
	}

	// Create new outpost template
	createRequest := data.ToCreateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	createResponse, err := r.client.CreateOutpostTemplate(ctx, createRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template Data Source",
			err.Error(),
		)
		return
	}

	if createResponse == nil || createResponse.Manual.TF == nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template Data Source",
			"SDK returned empty or invalid response. Please report this issue to the provider developers.",
		)
		return
	}

	// Populate computed values from API response
	data.TerraformModuleURL = types.StringPointerValue(createResponse.Manual.TF)

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
