// Copyright (c) Palo Alto Networks, Inc.
// SPDX-License-Identifier: MPL-2.0

package cloudonboarding

import (
	"context"
	"fmt"
	"strings"

	"github.com/PaloAltoNetworks/cortex-cloud-go/cloudonboarding"
	"github.com/PaloAltoNetworks/cortex-cloud-go/enums"

	models "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/cloud_onboarding"
	providerModels "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/provider"
	"github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/util"
	"github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/validators"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource               = &OutpostTemplateResource{}
	_ resource.ResourceWithModifyPlan = &OutpostTemplateResource{}
)

// NewOutpostTemplateResource is a helper function to simplify the provider implementation.
func NewOutpostTemplateResource() resource.Resource {
	return &OutpostTemplateResource{}
}

// OutpostTemplateResource is the resource implementation.
type OutpostTemplateResource struct {
	client *cloudonboarding.Client
}

// Metadata returns the resource type name.
func (r *OutpostTemplateResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_outpost_template"
}

// Schema defines the schema for the resource.
func (r *OutpostTemplateResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an outpost template.",
		Attributes: map[string]schema.Attribute{
			"cloud_provider": schema.StringAttribute{
				Description: fmt.Sprintf("The cloud service provider. Possible values are: \"%s\"", strings.Join(enums.AllCloudProviders(), "\", \"")),
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"custom_resources_tags": schema.SetNestedAttribute{
				Description: "Tags applied to any new resource created by " +
					"Cortex Cloud in the cloud environment." +
					"\n\nThe tag \"managed_by\" with the value " +
					"\"paloaltonetworks\" will always be applied by default.",
				MarkdownDescription: "Tags applied to any new resource created by " +
					"Cortex Cloud in the cloud environment." +
					"\n\nThe tag `managed_by` with the value " +
					"`paloaltonetworks` will be applied by default.",
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Description: "The tag key.",
							Required:    true,
						},
						"value": schema.StringAttribute{
							Description: "The tag value.",
							Required:    true,
						},
					},
				},
				Validators: []validator.Set{
					validators.TagsContainNoDuplicateKeys(),
				},
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"terraform_module_url": schema.StringAttribute{
				Description: "The download link for the Terraform module that is generated by Cortex Cloud upon successful creation of the outpost template. You may download and deploy this module to create the required infrastructure to conduct cloud workload scans in the configured cloud account.",
				MarkdownDescription: "The download link for the Terraform module that is generated by Cortex Cloud upon successful creation of the outpost template. You may download and deploy this module to create the required infrastructure to conduct cloud workload scans in the configured cloud account.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// Configure adds the provider-configured client to the resource.
func (r *OutpostTemplateResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured
	if req.ProviderData == nil {
		return
	}

	ctx = tflog.SetField(ctx, "resource_type", "outpost_template")
	ctx = tflog.SetField(ctx, "resource_operation", "Configure")
	tflog.Debug(ctx, "Configuring SDK client")

	client, ok := req.ProviderData.(*providerModels.CortexCloudSDKClients)

	if !ok {
		util.AddUnexpectedResourceConfigurationTypeError(&resp.Diagnostics, "*providerModels.CortexCloudSDKClients", req.ProviderData)
		return
	}

	r.client = client.CloudOnboarding
}

func (r *OutpostTemplateResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	ctx = tflog.SetField(ctx, "resource_type", "outpost_template")
	ctx = tflog.SetField(ctx, "resource_operation", "ModifyPlan")
	tflog.Debug(ctx, "Executing ModifyPlan")

	if req.State.Raw.IsNull() {
		return
	}

	var (
		cloudProviderPath = path.Root("cloud_provider")
		cloudProviderState basetypes.StringValue
		cloudProviderPlan basetypes.StringValue
		customResourceTagsPath = path.Root("custom_resources_tags")
		customResourcesTagsState basetypes.SetValue
		customResourcesTagsPlan basetypes.SetValue
	)

	resp.Diagnostics.Append(req.State.GetAttribute(ctx, cloudProviderPath, &cloudProviderState)...)
	resp.Diagnostics.Append(req.Plan.GetAttribute(ctx, cloudProviderPath, &cloudProviderPlan)...)
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, customResourceTagsPath, &customResourcesTagsState)...)
	resp.Diagnostics.Append(req.Plan.GetAttribute(ctx, customResourceTagsPath, &customResourcesTagsPlan)...)
	if resp.Diagnostics.HasError() {
		return
	}


	if !cloudProviderState.Equal(cloudProviderPlan) {
		resp.RequiresReplace = append(resp.RequiresReplace, cloudProviderPath)
	}
	
	if !customResourcesTagsState.Equal(customResourcesTagsPlan) {
		resp.RequiresReplace = append(resp.RequiresReplace, customResourceTagsPath)
	}
}

// Create creates the resource and sets the initial Terraform state.
func (r *OutpostTemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	defer util.PanicHandler(&resp.Diagnostics)

	var data models.OutpostTemplateModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create new outpost template
	createRequest := data.ToCreateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	createResponse, err := r.client.CreateOutpostTemplate(ctx, createRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template Resource",
			err.Error(),
		)
		return
	}

	if createResponse == nil || createResponse.Manual.TF == nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template Resource",
			"SDK returned empty or invalid response. Please report this issue to the provider developers.",
		)
		return
	}

	// Populate computed values from API response
	data.TerraformModuleURL = types.StringPointerValue(createResponse.Manual.TF)

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Read refreshes the Terraform state with the latest values.
func (r *OutpostTemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	defer util.PanicHandler(&resp.Diagnostics)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *OutpostTemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	defer util.PanicHandler(&resp.Diagnostics)
	
	ctx = tflog.SetField(ctx, "resource_type", "outpost_template")
	ctx = tflog.SetField(ctx, "resource_operation", "Update")
	
	// The resource should require replacement upon modifying any of the 
	// configurable attributes, but as a fallback we will remove the resource
	// from the state.
	resp.State.RemoveResource(ctx)
}

// Delete deletes the resource and removes it from the Terraform state on success.
func (r *OutpostTemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	defer util.PanicHandler(&resp.Diagnostics)
	resp.State.RemoveResource(ctx)
}
