// Copyright (c) Palo Alto Networks, Inc.
// SPDX-License-Identifier: MPL-2.0

package cloudonboarding

import (
	"context"
	"fmt"
	"strings"

	"github.com/PaloAltoNetworks/cortex-cloud-go/cloudonboarding"
	"github.com/PaloAltoNetworks/cortex-cloud-go/enums"

	models "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/cloud_onboarding"
	providerModels "github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/models/provider"
	"github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/util"
	"github.com/PaloAltoNetworks/terraform-provider-cortexcloud/internal/validators"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ ephemeral.EphemeralResource = &OutpostTemplateEphemeralResource{}
)

// NewOutpostTemplateEphemeralResource is a helper function to simplify the provider implementation.
func NewOutpostTemplateEphemeralResource() ephemeral.EphemeralResource {
	return &OutpostTemplateEphemeralResource{}
}

// OutpostTemplateEphemeralResource is the resource implementation.
type OutpostTemplateEphemeralResource struct {
	client *cloudonboarding.Client
}

// Metadata returns the resource type name.
func (r *OutpostTemplateEphemeralResource) Metadata(ctx context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_outpost_template"
}

// Schema defines the schema for the ephemeral.
func (r *OutpostTemplateEphemeralResource) Schema(ctx context.Context, req ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a CSP outpost template.",
		Attributes: map[string]schema.Attribute{
			"cloud_provider": schema.StringAttribute{
				Description: fmt.Sprintf("The cloud service provider. Possible values are: \"%s\"", strings.Join(enums.AllCloudProviders(), "\", \"")),
				Required:    true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						enums.AllCloudProviders()...,
					),
				},
			},
			"custom_resources_tags": schema.SetNestedAttribute{
				Description: "Tags applied to any new resource created by Cortex Cloud in the cloud environment." +
					"\n\nThe tag \"managed_by\" with the value \"paloaltonetworks\" will always be applied by default.",
				MarkdownDescription: "Tags applied to any new resource created by Cortex Cloud in the cloud environment." +
					"\n\nThe tag `managed_by` with the value `paloaltonetworks` will be applied by default.",
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Description: "The tag key.",
							Required:    true,
						},
						"value": schema.StringAttribute{
							Description: "The tag value.",
							Required:    true,
						},
					},
				},
				// TODO: enforce unique keys
				Validators: []validator.Set{
					validators.TagsContainNoDuplicateKeys(),
				},
			},
			"terraform_module_url": schema.StringAttribute{
				Description:         "The download URL for the Terraform module generated by Cortex Cloud. created template as a Terraform module, which you can then apply to permit Cortex Cloud to scan your cloud environment.",
				MarkdownDescription: "The full URL returned by Cortex Cloud when selecting the Terraform method of downloading the template. Opening this URL in your browser will begin a download of the created template as a Terraform module, which you can then apply to permit Cortex Cloud to scan your cloud environment.",
				Computed:            true,
			},
		},
	}
}

// Configure adds the provider-configured client to the ephemeral resource.
func (r *OutpostTemplateEphemeralResource) Configure(ctx context.Context, req ephemeral.ConfigureRequest, resp *ephemeral.ConfigureResponse) {
	// Prevent panic if the provider has not been configured
	if req.ProviderData == nil {
		return
	}

	ctx = tflog.SetField(ctx, "ephemeral_type", "outpost_template")
	ctx = tflog.SetField(ctx, "ephemeral_operation", "Configure")
	tflog.Debug(ctx, "Configuring SDK client")

	client, ok := req.ProviderData.(*providerModels.CortexCloudSDKClients)

	if !ok {
		util.AddUnexpectedResourceConfigurationTypeError(&resp.Diagnostics, "*http.Client", req.ProviderData)
		return
	}

	r.client = client.CloudOnboarding
}

func (r *OutpostTemplateEphemeralResource) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	defer util.PanicHandler(&resp.Diagnostics)

	ctx = tflog.SetField(ctx, "ephemeral_type", "outpost_template")
	ctx = tflog.SetField(ctx, "ephemeral_operation", "Open")

	// Retrieve values from config
	tflog.Debug(ctx, "Retrieving values from config")
	var plan models.OutpostTemplateModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create new ephemeral resource
	tflog.Debug(ctx, "Generating API request payload")
	createRequest := plan.ToCreateRequest(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Executing API request")
	createResponse, err := r.client.CreateOutpostTemplate(ctx, createRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template",
			err.Error(),
		)
		return
	}

	if createResponse == nil {
		resp.Diagnostics.AddError(
			"Error Creating Outpost Template",
			"SDK returned empty response. Please report this issue to the provider developers.",
		)
		return
	}

	// Populate computed values from API response
	plan.TerraformModuleURL = types.StringPointerValue(createResponse.Manual.TF)

	// Set state
	resp.Diagnostics.Append(resp.Result.Set(ctx, &plan)...)
}
